version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: GhostSthong567890@# # remove before production
      MYSQL_DATABASE: api_production
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-proot" ]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      RAILS_ENV: production
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
