services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "GhostSthong567890@#"
      MYSQL_DATABASE: api_production
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 10
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "GhostSthong567890@#"
      DB_NAME: api_production
      DATABASE_URL: "mysql2://root:GhostSthong567890%40%23@db:3306/api_production?encoding=utf8mb4"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
